version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: escola-vitor-prisma
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "7090:5432"
